### ISSUE TITLE
How to work with Shadows?

### ISSUE THREAD

**Issue by csantos1113** [Temzasse/stitches-native#10]
Stitches.dev core supports shadows as part of their theme object: https://stitches.dev/docs/tokens like:
```
shadows: {
  solidGrayLarge: `0px 0px 0 5px $gray400`
}
```
This css obviously won't work on react-native, because it expects an object like (see [react-native-shadow-generator](https://ethercreative.github.io/react-native-shadow-generator/)):
```
shadowColor: "#000",
shadowOffset: {
  width: 0,
  height: 9,
},
shadowOpacity: 0.48,
shadowRadius: 11.95,
elevation: 18,
```
and `textShadowColor`, `textShadowOffset`, `textShadowRadius` for Text.

# Questions
1. Should we remove `shadows` from the types (see https://github.com/Temzasse/stitches-native/blob/main/src/types/core.d.ts#L115) given that it won't work one to one? Right now `shadows` is not being used
2. I see the value of having shadows being part of the underline theme, **but...** how can we support them?

I found this library that transforms css strings into RN styled-object https://github.com/styled-components/css-to-react-native/blob/4f96cf6bb81b48894b53bce041512d495de715ba/src/transforms/util.js#L47 but seem not longer maintained :/

**Comment by Temzasse** [comment]
@csantos1113 this is a very good question 🤔 

The issue of shadows in RN is a particularly nasty one because of the whole mismatch between iOS and Android. There is basically no way to have unified looking shadows as part of the theme by providing a single token value because the shadows behave so differently on each platform (elevation system vs. proper customisable shadows).

What do you think, would it make sense to handle the shadows via `utils` since that way it is possible to change the returned style properties based on the platform?

```ts
import { Platform } from 'react-native';

const { ... } = createCss({
  utils: {
    shadow: () => (level: "small" | "medium" | "large") => {
      return {
        small:
          Platform.OS === "android"
            ? { elevation: 2 }
            : {
                shadowOffset: { width: 0, height: 1 },
                shadowRadius: 3,
                shadowOpacity: 0.1,
                shadowColor: "#000",
              },
        medium:
          Platform.OS === "android"
            ? { elevation: 5 }
            : {
                shadowOffset: { width: 0, height: 3 },
                shadowRadius: 6,
                shadowOpacity: 0.2,
                shadowColor: "#000",
              },
        large:
          Platform.OS === "android"
            ? { elevation: 10 }
            : {
                shadowOffset: { width: 0, height: 6 },
                shadowRadius: 12,
                shadowOpacity: 0.4,
                shadowColor: "#000",
              },
      }[level];
    },
  },
});
```

And then use it like this:

```tsx
const Comp = styled('View', {
  shadow: 'large',
});
```

We could document this in the README with a comprehensive example like the one above.
