### ISSUE TITLE
Flat list missing props when styled is used

### ISSUE THREAD

**Issue by norman-ags** [Temzasse/stitches-native#19]
When `FlatList` is used in styled, it loses its props, see screenshot below: 
![image](https://user-images.githubusercontent.com/63862061/135253293-57cc64fc-eb78-4e84-b7fb-562a867e32ef.png)

Output should be: 
![image](https://user-images.githubusercontent.com/63862061/135253219-da13e101-b4b0-4085-9344-5dbacab32739.png)

**Comment by Temzasse** [comment]
The types should work okay if you have any styles defined, eg:

```ts
const SomeList = styled('FlatList', {
  flex: 1,
});
```

I'm not sure why the empty object breaks the typings 🤔  The typings are kindah a black box for me since they have been mostly copy-pasted from the main Stitches repo so it's very difficult to fix these kind of issues.

How relevant is the empty object use case in real life? I think this issue shouldn't affect too much in real world usage, right?

**Comment by norman-ags** [comment]
Oh, that's a nice workaround. Thanks @Temzasse!
