### ISSUE TITLE
`as` prop

### ISSUE THREAD

**Issue by winterscar** [Temzasse/stitches-native#27]
According to the stitches documentation and the stitches-native types, styled() components should accept an `as` prop to optionally override the rendered component.

However, as best I can tell, this doesn't seem to work in stitches native.

Is there any particular reason why? Is

**Comment by Temzasse** [comment]
On the Web having the `as` prop makes sense since semantics for accessibility are conveyed via semantic HTML tags like `section`, `p`, `strong`, etc.

However on the native side [accessibility](https://reactnative.dev/docs/accessibility) is handled differently and changing the rendered component with the `as` prop would be quite confusing since different native components have such a different API for props. For example changing a `Text` to a `View` dynamically would cause a crash since all text should always be rendered within the `Text` component.
